pipeline:
  mytask:
    image: node:alpine
    commands:
      - docker build -t newone today
      - docker run --name newins newone
      - echo docker ps
      - echo "done"
    when:
      event: push
